# Generated by Django 5.1.7 on 2025-03-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_deck_id_remove_user_id_alter_deck_deck_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(max_length=50)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'unique_together': {('user', 'deck')},
            },
        ),
    ]
